In [1]:
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]]) #3x4 matrix
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
valoraciones[0][1]

7

In [4]:
valoraciones[0,1] #same as before

7

In [5]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]]) #3x2x4 matrix
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [6]:
valoraciones2[0,1,2]

5

In [7]:
np.zeros((3,2,4)) #3x2x4 matrix of zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
valoraciones2 + np.ones((3,2,4)) #sum valoraciones2 to a 3x2x4 matrix of ones

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [9]:
np.mean(valoraciones2) #mean of the values in the array

6.458333333333333

In [10]:
np.mean(valoraciones2,axis=0) #mean of all values in the first axis (first dimension of the array) - the output will be a 2x4 matrix with the means of the first dimension

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [11]:
np.mean(valoraciones2,axis=1) #3x4

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [12]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2)) #convert a list into a given dimension - number of elements must agree with the dimension

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
#np.median(df['Column1']) if we're working with df

In [14]:
np.random.rand(2,2) #array of random elements of a given dimension

array([[0.7590972 , 0.05050924],
       [0.03808009, 0.78487257]])